# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ai_route_prototype_development

test:
  <<: *default
  database: ai_route_prototype_test

production:
  <<: *default
  database: ai_route_prototype_production
  username: ai_route_prototype
  password: <%= ENV["AI_ROUTE_PROTOTYPE_DATABASE_PASSWORD"] %>
